version: '3.8'

services:
  chroma:
    image: chromadb/chroma
    container_name: chroma
    ports:
      - 8888:8888
    volumes:
      - ./stateful_volumes/chroma:/chroma/chroma
    command: "--workers 1 --host 0.0.0.0 --port 8888 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    environment:
      - IS_PERSISTENT=TRUE
      - CHROMA_SERVER_AUTHN_PROVIDER=${CHROMA_SERVER_AUTHN_PROVIDER}
      - CHROMA_SERVER_AUTHN_CREDENTIALS_FILE=${CHROMA_SERVER_AUTHN_CREDENTIALS_FILE}
      - CHROMA_SERVER_AUTHN_CREDENTIALS=${CHROMA_SERVER_AUTHN_CREDENTIALS}
      - CHROMA_AUTH_TOKEN_TRANSPORT_HEADER=${CHROMA_AUTH_TOKEN_TRANSPORT_HEADER}
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
      - CHROMA_OTEL_EXPORTER_ENDPOINT=${CHROMA_OTEL_EXPORTER_ENDPOINT}
      - CHROMA_OTEL_EXPORTER_HEADERS=${CHROMA_OTEL_EXPORTER_HEADERS}
      - CHROMA_OTEL_SERVICE_NAME=${CHROMA_OTEL_SERVICE_NAME}
      - CHROMA_OTEL_GRANULARITY=${CHROMA_OTEL_GRANULARITY}
      - CHROMA_SERVER_NOFILE=${CHROMA_SERVER_NOFILE}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # redis:
  #   image: bitnami/redis:latest
  #   container_name: aatl-redis
  #   ports:
  #     - 6379:6379
  #   restart: always
  #   volumes:
  #     - ./stateful_volumes/redis:/bitnami/redis/data
  #   env_file:
  #     - .env
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 2s
  #     timeout: 5s
  #     retries: 3

networks:
  default: 
    name: coursera_ppt
